language: python

sudo: true

addons:
  apt:
    packages:
      - libblas3
      - liblapack3
      - libhdf5-serial-dev
      - hdf5-tools

matrix:
  include:
    - os: linux
      python: 3.5
      sudo: required

    - os: linux
      python: 3.6
      sudo: required

    - os: linux
      python: 3.7
      sudo: required
      dist: xenial

    - os: osx
      language: generic
      python: "3.5"

    - os: osx
      language: generic
      python: "3.6"

    - os: osx
      python: "3.7"
      language: generic

before_script:
  - if [ $TRAVIS_OS_NAME = osx ]; then brew install hdf5; fi

cache:
  apt: true
  directories:
    - $HOME/.cache/pip
    - $HOME/Library/Caches/Homebrew
    - /usr/local/Cellar

# hdf5-tools
install:
  - "pip3 install wheel pip setuptools --upgrade"
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pip3 install --user -r requirements.txt; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then pip3 install -r requirements-dev.txt; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then pip3 install -r requirements.txt; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then pip3 install -r requirements-dev.txt; fi

script:
  - python3 --version
  - pytest -v -s
  - py.test -v --cov=tableseries --cov-report xml

after_success:
  - codecov -e $TRAVIS_PYTHON_VERSION

before_deploy: "echo 'ready'"

deploy:
  provider: pypi
  user: nooperpudd
  password:
    secure:
  distributions: "sdist"
  on:
    tags: true
    python: '3.6'