language: python

addons:
  apt:
    packages:
      - libhdf5-serial-dev
      - hdf5-tools

matrix:
  include:
    - os: linux
      python: 3.5
      sudo: required

    - os: linux
      python: 3.6
      sudo: required

    - os: linux
      python: 3.7
      sudo: required
      dist: xenial

    - os: osx
      python: 3.5
      language: generic

    - os: osx
      python: 3.6
      language: generic

    - os: osx
      python: 3.7
      language: generic

before_script:
  - if [ $TRAVIS_OS_NAME = osx ]; then brew install gcc; brew link --overwrite --dry-run gcc; brew install hdf5; fi

# hdf5-tools
install:
  - python -c "import struct; print(struct.calcsize('P') * 8)"
  - "pip install wheel pip setuptools --upgrade"
  - "pip install -r requirements.txt --upgrade"
  - "pip install pytest"

script:
  - python setup.py build_ext --inplace
  - pytest -v -s

before_deploy: "echo 'ready'"

deploy:
  provider: pypi
  user: nooperpudd
  password:
    secure:
  distributions: "sdist"
  on:
    tags: true
    python: '3.6'